In [12]:
import requests
import pandas as pd
from tqdm import tqdm 
from bs4 import BeautifulSoup

In [8]:
df = pd.read_csv('books.csv')
df.head()

,title,rating,price,stock,book_link,img_link
0,A Light in the Attic,Three,51.77,In stock,https://books.toscrape.com/catalogue/a-light-i...,https://books.toscrape.com/../media/cache/2c/d...
1,Tipping the Velvet,One,53.74,In stock,https://books.toscrape.com/catalogue/tipping-t...,https://books.toscrape.com/../media/cache/26/0...
2,Soumission,One,50.10,In stock,https://books.toscrape.com/catalogue/soumissio...,https://books.toscrape.com/../media/cache/3e/e...
3,Sharp Objects,Four,47.82,In stock,https://books.toscrape.com/catalogue/sharp-obj...,https://books.toscrape.com/../media/cache/32/5...
4,Sapiens: A Brief History of Humankind,Five,54.23,In stock,https://books.toscrape.com/catalogue/sapiens-a...,https://books.toscrape.com/../media/cache/be/a...

In [42]:
data = []

for link in tqdm(df['book_link']):
    res = requests.get(link)
    soup = BeautifulSoup(res.text , 'html.parser')

    typ = soup.find('ul' , class_ = 'breadcrumb').find_all('a')[2].text

    upc = soup.find('table' , class_ = 'table table-striped').find_all('td')[0].text
    price_x   = soup.find('table' , class_ = 'table table-striped').find_all('td')[2].text[2:]
    price_i   = soup.find('table' , class_ = 'table table-striped').find_all('td')[3].text[2:]
    tax       = soup.find('table' , class_ = 'table table-striped').find_all('td')[4].text
    qn        = soup.find('table' , class_ = 'table table-striped').find_all('td')[5].text
    reviews   = soup.find('table' , class_ = 'table table-striped').find_all('td')[6].text
    
    data.append([typ , price_x , price_i , tax , qn , upc , reviews])

100%|██████████| 1000/1000 [12:30<00:00,  1.33it/s]

In [44]:
df = pd.DataFrame(data , columns = ['category' , 'price_e_tax' , 'price_i_tax' , 'tax' , 'quantity' , 'upc' , 'reviews' ])

df.head()

,category,price_e_tax,price_i_tax,tax,quantity,upc,reviews
0,Poetry,51.77,51.77,Â£0.00,In stock (22 available),a897fe39b1053632,0
1,Historical Fiction,53.74,53.74,Â£0.00,In stock (20 available),90fa61229261140a,0
2,Fiction,50.10,50.10,Â£0.00,In stock (20 available),6957f44c3847a760,0
3,Mystery,47.82,47.82,Â£0.00,In stock (20 available),e00eb4fd7b871a48,0
4,History,54.23,54.23,Â£0.00,In stock (20 available),4165285e1663650f,0

In [46]:
df.to_csv('data.csv' , index = False)